apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: indexer-scaledobject
  namespace: k8s-ops
spec:
  scaleTargetRef:
    name: indexer
  minReplicaCount: 1
  maxReplicaCount: 5
  pollingInterval: 15
  cooldownPeriod: 60
  triggers:
    - type: nats-jetstream
      metadata:
        natsServerMonitoringEndpoint: nats.k8s-ops.svc.cluster.local:8222
        account: $G
        stream: K8S_EVENTS
        consumer: INDEXER
        lagThreshold: "100"
